#[derive(Clone, Copy, Debug)]
pub enum Instr {
    Block(usize),
    GlobalLookup(usize),
    ClosureReturn(usize),
    Double(f64),
    InstVarLookup(usize),
    InstVarSet(usize),
    Int(isize),
    Pop,
    Return,
    Send(usize, usize),
    String(usize),
    SuperSend(usize, usize),
    Symbol(usize),
    VarLookup(usize, usize),
    VarSet(usize, usize),
}

#[derive(Clone, Copy, Debug)]
pub enum Primitive {
    Add,
    And,
    As32BitSignedValue,
    As32BitUnsignedValue,
    AsInteger,
    AsString,
    AsSymbol,
    AtRandom,
    BitXor,
    Class,
    Cos,
    Concatenate,
    Div,
    DoubleDiv,
    Equals,
    Exit,
    Fields,
    FromString,
    Global,
    GlobalPut,
    GreaterThan,
    GreaterThanEquals,
    Halt,
    Hashcode,
    Inspect,
    InstVarAt,
    InstVarAtPut,
    InstVarNamed,
    Length,
    Load,
    LessThan,
    LessThanEquals,
    Methods,
    Mod,
    Mul,
    Name,
    NotEquals,
    New,
    ObjectSize,
    Perform,
    PerformInSuperClass,
    PerformWithArguments,
    PerformWithArgumentsInSuperClass,
    PositiveInfinity,
    PrimSubstringFromTo,
    PrintNewline,
    PrintString,
    RefEquals,
    Rem,
    Restart,
    Round,
    Shl,
    Shr,
    Sin,
    Sqrt,
    Sub,
    Superclass,
    /// Is this `value` (0), `value:` (1), or `value:with:` (2)?
    Value(u8),
}
